### ISSUE TITLE
数据集Lastfm数量不对？

### ISSUE THREAD

**Issue by TangJiakai** [chenzhao-hfut/FairMI#1]
官方Lastfm数据集的信息是
![image](https://user-images.githubusercontent.com/58941474/227076195-ffd62753-9428-48a8-8903-342de4c41ac5.png)
可是论文里报的是
![image](https://user-images.githubusercontent.com/58941474/227076219-716c7a95-8781-476b-a715-d9ea9eb79624.png)
没有这么多用户、物品吧？

**Comment by chenzhao-hfut** [comment]
感谢您的关注。

我们的做法是对原始的 lastfm-360K 数据集进行随机抽样。

原始数据集地址：http://ocelma.net/MusicRecommendationDataset/lastfm-360K.html

**Comment by TangJiakai** [comment]
噢噢这样啊，那您数据处理代码有吗？想借用一下😊

**Comment by chenzhao-hfut** [comment]
您好，在之后我们会更新数据处理版本的代码

**Comment by TangJiakai** [comment]
您大概什么时候给数据处理代码嘞？

**Comment by TangJiakai** [comment]
![image](https://user-images.githubusercontent.com/58941474/228560871-034b33dc-1fe6-4ca2-a112-bd201ffe1391.png)
我处理了一下，似乎比原文又多了很多。。。

**Comment by chenzhao-hfut** [comment]
不好意思，给您带来了些许的困惑。

首先，原始的LastFM-360K数据集是比较庞大的，这会导致在做 ranking 的时候会非常耗时（ps，计算公平性指标也会很耗时），因此我们选择随机抽取源数据集中的子集进行实验（我当时取的实际比例大概在20~30%）

其次，关于预处理代码，我本人会在论文正式发表前更新。

**Comment by TangJiakai** [comment]
好的，没错，LastFM确实很大，不好调参啊啊🤣
